### ISSUE TITLE
CLA cannot be accessed

### ISSUE THREAD

**Issue by hislop** [beloitcollegecomputerscience/OED#78]
The Readme file has a link to a CLA in the contributions section.  Clicking on that link produces the following error message:  You need permission

This form can only be viewed by users in the owner's organization.

Try contacting the owner of the form if you think this is a mistake. Learn More.

**Comment by huss** [comment]
This was my fault. The Google Form accessed was with the wrong link and the default setting to limit to only Beloit College was an issue. This should now be resolved.
